### ISSUE TITLE
Auto deploy somewhere with github actions

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/frontend#110] opened 2021-11-27 19:19 UTC
Currently, @razzeee deployed the website using Vercel, same way we have done a long time ago. it would be nice to auto-deploy it somewhere else using Github Actions, and maybe do the same for release versions in the future.

cc @barthalion any opinions?

**Comment by bilelmoussaoui** [comment] 2021-11-27 19:20
ah seems to be kind of a duplicate of https://github.com/flathub/frontend/issues/62

**Comment by razzeee** [comment] 2021-11-27 19:29
I think best would be to first do this for the backend, if we want a real staging env

**Comment by nedrichards** [comment] 2022-01-30 21:46
Yeah, I'd say this is a dupe of 62 - we want a full release process, staging for testing etc. - unless you're suggesting something like a per branch CD (in which case please reopen) I'm going to close this for now.

**Closed by nedrichards** 2022-01-30 21:46 UTC
